// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_aes_demo.h for the primary calling header

#ifndef VERILATED_VTB_AES_DEMO___024ROOT_H_
#define VERILATED_VTB_AES_DEMO___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_aes_demo__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_aes_demo___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_aes_demo__DOT__clk;
        CData/*0:0*/ tb_aes_demo__DOT__start;
        CData/*0:0*/ tb_aes_demo__DOT__done;
        CData/*2:0*/ tb_aes_demo__DOT__dut__DOT__ps;
        CData/*3:0*/ tb_aes_demo__DOT__dut__DOT__round;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__s0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__s1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__s2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__s3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__out0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__out1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__out2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m0__DOT__out3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__s0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__s1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__s2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__s3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__out0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__out1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__out2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m1__DOT__out3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__s0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__s1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__s2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__s3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__out0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__out1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__out2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m2__DOT__out3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__s0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__s1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__s2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__s3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__out0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__out1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__out2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__m3__DOT__out3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__b2;
    };
    struct {
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__b0;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__b1;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__b2;
        CData/*7:0*/ tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__b3;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__0__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__0__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__1__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__1__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__2__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__2__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__3__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__3__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__4__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__4__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__5__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__5__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__6__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__6__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__7__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__7__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__8__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__8__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__9__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x3__9__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__10__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__10__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__11__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m0__DOT__x2__11__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__12__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__12__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__13__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__13__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__14__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__14__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__15__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__15__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__16__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__16__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__17__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__17__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__18__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__18__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__19__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__19__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__20__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__20__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__21__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x3__21__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__22__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__22__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__23__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m1__DOT__x2__23__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__24__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__24__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__25__Vfuncout;
    };
    struct {
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__25__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__26__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__26__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__27__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__27__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__28__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__28__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__29__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__29__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__30__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__30__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__31__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__31__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__32__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__32__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__33__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x3__33__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__34__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__34__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__35__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m2__DOT__x2__35__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__36__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__36__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__37__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__37__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__38__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__38__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__39__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__39__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__40__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__40__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__41__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__41__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__42__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__42__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__43__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__43__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__44__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__44__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__45__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x3__45__b;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__46__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__46__a;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__47__Vfuncout;
        CData/*7:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__m3__DOT__x2__47__a;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_aes_demo__DOT__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__plain_txt;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__cipher_txt;
        IData/*31:0*/ tb_aes_demo__DOT__count;
        IData/*31:0*/ tb_aes_demo__DOT__start_time;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__dut__DOT__state;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__dut__DOT__key;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__dut__DOT__sbout;
        VlWide<4>/*127:0*/ tb_aes_demo__DOT__dut__DOT__shift_out;
        VlWide<44>/*1407:0*/ tb_aes_demo__DOT__dut__DOT__r_key_raw;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__48__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__48__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__49__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__49__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__50__Vfuncout;
    };
    struct {
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__50__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__51__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__51__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__53__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__53__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__54__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__54__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__55__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__55__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__56__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__56__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__58__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__58__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__59__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__59__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__60__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__60__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__61__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__61__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__63__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__63__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__64__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__64__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__65__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__65__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__66__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__66__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__68__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__68__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__69__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__69__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__70__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__70__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__71__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__71__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__73__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__73__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__74__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__74__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__75__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__75__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__76__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__76__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__78__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__78__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__79__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__79__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__80__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__80__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__81__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__81__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__83__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__83__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__84__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__84__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__85__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__85__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__86__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__86__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__88__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__88__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__89__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__89__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__90__Vfuncout;
    };
    struct {
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__90__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__91__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__91__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__93__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__93__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__94__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__94__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__95__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__95__x;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__96__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_aes_demo__DOT__dut__DOT__passkey__DOT__RotWord__96__x;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<VlWide<4>/*127:0*/, 11> tb_aes_demo__DOT__dut__DOT__round_key;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__0__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__1__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__2__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__3__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__4__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__5__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__6__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__7__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__8__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__9__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__10__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__11__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__12__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__13__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__14__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__sb__DOT__sbox_inst__BRA__15__KET____DOT__dut__DOT__sbox_mem;
        VlUnpacked<IData/*31:0*/, 44> tb_aes_demo__DOT__dut__DOT__passkey__DOT__w;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__4__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__8__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__12__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__16__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__20__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__24__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__28__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__32__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__36__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__bx0__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__bx1__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__bx2__DOT__sbox_mem;
        VlUnpacked<CData/*7:0*/, 256> tb_aes_demo__DOT__dut__DOT__passkey__DOT__key_gen__BRA__40__KET____DOT__spl_key__DOT__bx3__DOT__sbox_mem;
        VlUnpacked<IData/*31:0*/, 44> __Vtrigprevexpr___TOP__tb_aes_demo__DOT__dut__DOT__passkey__DOT__w__0;
        VlUnpacked<IData/*31:0*/, 44> __Vtrigprevexpr___TOP__tb_aes_demo__DOT__dut__DOT__passkey__DOT__w__1;
        VlUnpacked<CData/*0:0*/, 4> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerVec<2> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_aes_demo__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_aes_demo___024root(Vtb_aes_demo__Syms* symsp, const char* v__name);
    ~Vtb_aes_demo___024root();
    VL_UNCOPYABLE(Vtb_aes_demo___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
